name: media_list_view
description: "A Flutter package that extends Photo View to provide a gesture-sensitive, zoomable media list view."
version: 1.0.2
homepage: "https://github.com/TrongNghiaB/media_list_view"
repository: "https://github.com/TrongNghiaB/media_list_view"
issue_tracker: "https://github.com/TrongNghiaB/media_list_view/issues"
documentation: "https://github.com/TrongNghiaB/media_list_view"
license: MIT

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.6.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.15.0

dev_dependencies:
  test: ^1.16.0-nullsafety.17
  flutter_test:
    sdk: flutter

flutter:

platforms:
  android:
  ios:
